{% set name = "ptsnet" %}
{% set version = "0.0.11" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 16f9cf98890928ef2e8d7846e4cded0bde79dd6fa770a5f90fefd65655d1e41a

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ mpi }}                              # [build_platform != target_platform and mpi == "openmpi"]
  host:
    - pip
    - python
    - numpy
    - scipy
    - networkx
    - wntr
    - h5py
    - {{ mpi }}
  run:
    - python
    - {{ mpi }}

test:
  imports:
    - ptsnet
    - ptsnet.arrays
    - ptsnet.epanet
    - ptsnet.parallel
    - ptsnet.profiler
    - ptsnet.results
    - ptsnet.simulation
    - ptsnet.utils
  commands:
    - python -c "import ptsnet.PTSNETSimulation; sim = PTSNETSimulation()"

about:
  home: "https://github.com/gandresr/PTSNET"
  license: "The Unlicense (Unlicense)"
  license_family: OTHER
  license_file: 
  summary: "Parallel Transient Simulation in Water Networks"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - gandresr
