package:
  name: "ptsnet"
  version: "0.0.2"

source:
  git_rev: v1.3.1
  git_url: https://github.com/gandresr/PTSNET

requirements:
  host:
    - python
    - setuptools
  build:
    - python
  run:
    - python
    - numpy
    - pandas
    - networkx
    - openmpi
    - openmpi-mpicc
    - mpi4py
    - tqdm

about:
  home: https://github.com/gandresr/PTSNET
  license: Unlicense
  license_familY: Unlicense
  license_file: LICENSE
  summary: "Parallel Transient Simulation in Water Networks"

extra:
  recipe-maintainers:
    - gandresr