{% set name = "ptsnet" %}
{% set version = "0.0.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: daea7d2ccb035dbd1ec7aafdceecebee146f244b9389f6befa401d21fbfff8f8

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - numba
    - scipy
    - wntr
    - networkx
    - h5py
    - mpi4py
    - tqdm

test:
  imports:
    - ptsnet
    - ptsnet.arrays
    - ptsnet.epanet
    - ptsnet.parallel
    - ptsnet.profiler
    - ptsnet.results
    - ptsnet.simulation
    - ptsnet.utils

about:
  home: "https://github.com/gandresr/PTSNET"
  license: "The Unlicense (Unlicense)"
  license_family: OTHER
  license_file: 
  summary: "Parallel Transient Simulation in Water Networks"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - gandresr
