{% set name = "ptsnet" %}
{% set version = "0.0.12" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  # If getting the source from GitHub, remove the line above,
  # uncomment the line below, and modify as needed. Use releases if available:
  # url: https://github.com/simplejson/simplejson/releases/download/{{ version }}/simplejson-{{ version }}.tar.gz
  # and otherwise fall back to archive:
  # url: https://github.com/simplejson/simplejson/archive/v{{ version }}.tar.gz
  sha256: d58439c548433adcda98e695be53e526ba940a4b9c44fb9a05d92cd495cdd47f
  # sha256 is the preferred checksum -- you can get it for a file with:
  #  `openssl sha256 <file name>`.
  # You may need the openssl package, available on conda-forge:
  #  `conda install openssl -c conda-forge``

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
  run:
    - python
    - numpy
    - numba
    - scipy
    - wntr
    - networkx
    - h5py
    - mpi4py
    - tqdm

test:
  imports:
    - ptsnet
    - ptsnet.arrays
    - ptsnet.epanet
    - ptsnet.parallel
    - ptsnet.profiler
    - ptsnet.results
    - ptsnet.simulation
    - ptsnet.utils

about:
  home: "https://github.com/gandresr/PTSNET"
  license: "The Unlicense (Unlicense)"
  license_family: OTHER
  license_file: 
  summary: "Parallel Transient Simulation in Water Networks"
  doc_url: 
  dev_url: 

extra:
  recipe-maintainers:
    - gandresr
